sonar.projectKey=vulreport
sonar.projectName=VulReport
sonar.sources=app
sonar.sourceEncoding=UTF-8

# Python reports can be added later if needed:
# sonar.python.bandit.reportPaths=reports/bandit.json
