# Generated by Django 5.2.12 on 2026-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cve_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='finding',
            name='source_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
