# Generated by Django 5.2.12 on 2026-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_finding_cve_id_finding_source_urls_report_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="company_logo_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="report",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="report",
            name="custom_header",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
