# Generated by Django 5.2.12 on 2026-03-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_report_branding_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_logo",
            field=models.ImageField(blank=True, null=True, upload_to="companies/"),
        ),
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
