# Generated by Django 5.2.12 on 2026-03-30 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_user_profile_and_company_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owned_organizations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "organizations", "ordering": ("name",)},
        ),
        migrations.AddField(
            model_name="report",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="confidentiality_mark",
            field=models.CharField(blank=True, default="CONFIDENTIEL", max_length=30),
        ),
        migrations.AddField(
            model_name="report",
            name="public_share_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="public_share_token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="report",
            name="approved_by",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="approved_reports", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="OrganizationMembership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("role", models.CharField(choices=[("owner", "Owner"), ("member", "Member")], default="member", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="core.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organization_memberships", to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "organization_memberships", "unique_together": {("organization", "user")}},
        ),
        migrations.CreateModel(
            name="ReportOrganizationShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="report_shares", to="core.organization")),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="organization_shares", to="core.report")),
            ],
            options={"db_table": "report_organization_shares", "unique_together": {("report", "organization")}},
        ),
        migrations.AddField(
            model_name="organization",
            name="members",
            field=models.ManyToManyField(related_name="organizations", through="core.OrganizationMembership", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="report",
            name="organizations",
            field=models.ManyToManyField(blank=True, related_name="shared_reports", through="core.ReportOrganizationShare", to="core.organization"),
        ),
        migrations.CreateModel(
            name="FindingComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="finding_comments", to=settings.AUTH_USER_MODEL)),
                ("finding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.finding")),
            ],
            options={"db_table": "finding_comments", "ordering": ("created_at",)},
        ),
    ]
