# Generated by Django 5.2.12 on 2026-03-30 16:43

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_profile_ids(apps, schema_editor):
    User = apps.get_model('core', 'User')
    used_ids = set(User.objects.exclude(profile_id__isnull=True).exclude(profile_id='').values_list('profile_id', flat=True))

    for user in User.objects.all():
        if user.profile_id:
            continue
        while True:
            candidate = f"VR-{uuid.uuid4().hex[:8].upper()}"
            if candidate not in used_ids:
                user.profile_id = candidate
                user.save(update_fields=['profile_id'])
                used_ids.add(candidate)
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_organizationmembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_id',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('declined', 'Refusee')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friend_requests',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friend_request_direction'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='prevent_self_friend_request')],
            },
        ),
        migrations.RunPython(populate_profile_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='profile_id',
            field=models.CharField(blank=True, editable=False, max_length=16, unique=True),
        ),
    ]
